package enigmafinal;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.ws.BindingProvider;

/**
 *
 * @author NipuNa NiraNjaNa
 */
public class login extends javax.swing.JFrame {

    int loginCount;
    int attempt;
    int set = 0;
    String uid;
    Date d2;
    String uname;
    SimpleDateFormat sdf;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        forgotpw.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userid = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        forgotpw = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System - Tech Ngine");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books-2-icon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, 120));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        userid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                useridKeyTyped(evt);
            }
        });
        jPanel3.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, 40));

        passWord.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passWord.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordActionPerformed(evt);
            }
        });
        jPanel3.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("User Name ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 30));

        loginbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/456456456456.png"))); // NOI18N
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        jPanel3.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, 30));

        forgotpw.setText("Forgot Password ?");
        forgotpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpwMouseClicked(evt);
            }
        });
        jPanel3.add(forgotpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 200, 140, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 550, 220));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("All Rights Reserved . Enigma");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 30));

        jButton2.setText("Contact Administration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 467, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Welcome to the Digital Student Management System - Enigma");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Management System ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 510, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 798, 491));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 515));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        passWord.grabFocus();
    }//GEN-LAST:event_useridActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void passWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordActionPerformed
        systemLogin();
    }//GEN-LAST:event_passWordActionPerformed

    private void forgotpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpwMouseClicked
        pwRecovery();
    }//GEN-LAST:event_forgotpwMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        systemLogin();
    }//GEN-LAST:event_loginbtnActionPerformed

    private void useridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_useridKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotpw;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables

    private void pwRecovery() {
        System.out.println("Forgot Password?");
        int i = JOptionPane.showConfirmDialog(this, "Forgot Password?", "Forgot Password?", JOptionPane.NO_OPTION);
        if (i == 0) {
            JOptionPane.showMessageDialog(rootPane, "       Forgot password...!");
            resetlog r = new resetlog();
            r.setVisible(true);
            this.dispose();
        } else {

        }
    }

    private void showLoginMSG() {
        userid.setText(null);
        passWord.setText(null);
        userid.grabFocus();
        if (loginCount == 0) {
            forgotpw.setVisible(true);
            JOptionPane.showMessageDialog(this, "1st Attempt Fail..!");
        } else if (loginCount == 1) {
            JOptionPane.showMessageDialog(rootPane, "2nd Attempt Failed..!");
        } else if (loginCount == 2) {
            JOptionPane.showMessageDialog(rootPane, "Your Last Attempt Failed..!");
            userid.setEnabled(false);
            passWord.setEnabled(false);
            forgotpw.setForeground(Color.red);
            resetlog re = new resetlog("Forget Password");
            re.setVisible(true);
            this.dispose();

            snapShot();
            JOptionPane.showMessageDialog(rootPane, "Please Check Your Security Question Please???");
            loginbtn.setVisible(false);

        }
    }

    private void snapShot() {
        /*Security protocol goes here
         Webcam starts with 3rd attempt
         by 3rd attempt failure, capture webcam image, save to lms--> security table under forced login
         generate random password under "Super_Admin" username feed it into login table
         */
    }

    private void sysClock() {

        final int timeRun = 0;
        new Thread() {
            public void run() {
                while (timeRun == 0) {
                    Calendar cal = new GregorianCalendar();

                    String user = userid.getText();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int am_pm = cal.get(Calendar.AM_PM);

                    String AMPM = "";
                    if (am_pm == 0) {
                        AMPM = "AM";
                    } else {
                        AMPM = "PM";
                    }

                    String time = hour + ":" + min + ":" + sec;
                    String define = "loged";

                    Date today = new Date();
                    DateFormat df = DateFormat.getDateInstance(DateFormat.LONG, Locale.US);
                    String strDate = df.format(today);

                    String date = new SimpleDateFormat("yyyy-MM-dd").format(today);

                    String datenTime = date + " " + time + " " + AMPM;
                    try {
                        DB.iud("update user set lastlogin='" + datenTime + "'  where userid ='" + uname + "'");
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
        }.start();

        try {
            DB.iud("update user set  logstate='loged' where userid ='" + uname + "'");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void systemLogin() {
        try {
            String user = userid.getText();
            String pw = new String(passWord.getPassword());

            loginformation.inforfilepath.initLogger();
            Logger log = Logger.getLogger("finalprojectlog");

            ResultSet l = DB.search("select* from user where username='" + userid.getText() + "'");
            if (l.next()) {
                ResultSet k = DB.search("select* from user where pw ='" + pw + "'");
                if (k.next()) {
                    ResultSet rs = DB.search("select* from user where username='" + userid.getText() + "' and pw ='" + pw + "'");
                    if (rs.next()) {
                        String i = rs.getString("status");
                        String y = rs.getString("logstate");
                        uname = rs.getString("userid");
                        if (i.equals("Active") && y.equals("Signed_out")) {
                            userid.setEditable(false);
                            passWord.setEditable(false);
                            loginbtn.setEnabled(false);
                            MainGUI m = new MainGUI();
                            m.activeUser(uname);
                            m.setVisible(true);

                            sysClock();
                            this.dispose();

                        } else if (i.equals("Active") && y.equals("loged")) {
                            resetlog re = new resetlog("Login Failed");
                            re.setVisible(true);
                            this.dispose();

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Unable to Connect...!");

                        }
                    } else {
                        showLoginMSG();
                        loginCount++;
                    }
                } else {
                    showLoginMSG();
                    loginCount++;
                }
            } else {
                showLoginMSG();
                loginCount++;

            }

        } catch (java.sql.SQLException e) {
            // e.printStackTrace();
            setrestore();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    private void setrestore() {
        try {
            try {
                ResultSet rs = DB.search("select * from institute");
                if (rs.first()) {

                }
            } catch (java.sql.SQLException e) {
                restore r = new restore();
                r.setVisible(true);
                this.dispose();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
