/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigmafinal;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author danushka nandalochan
 */
public class resetlog extends javax.swing.JFrame {

    int attempt;
    int attempta;

    /**
     * Creates new form resetlog
     */
    public resetlog() {
        initComponents();
        operation();
    }

    resetlog(String forget_Password) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        operation();
        jLabel5.setText(forget_Password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        body = new javax.swing.JComboBox<>();
        answer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 300, 30));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 300, 30));

        body.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 300, 30));
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 300, 40));

        jLabel1.setText("Enter Your Answer:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 40));

        jLabel4.setText("Select Your One Security Question:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 40));

        jLabel3.setText("Enter Your User Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 40));

        jLabel2.setText("Enter Your User ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 30));

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 150, 50));
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 310, 50));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Forget Password ?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        name.grabFocus();
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginformation.inforfilepath.initLogger();
        Logger log = Logger.getLogger("finalprojectlog");
        if (name.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Invalid Data....!");
            id.setText(null);
            name.setText(null);
            id.grabFocus();

        } else {
            if (jLabel5.getText().equals("Login Failed")) {

                try {

                    String k = id.getText();

                    ResultSet f = DB.search("select * from user where staff_staffid='" + k + "'");
                    if (f.next()) {
                        String k1 = f.getString("userid");
                        ResultSet rc1 = DB.search("select * from securityquestions where question='" + body.getSelectedItem() + "' and status='Active' ");
                        if (rc1.next()) {
                            String a = rc1.getString("questionid");
                            ResultSet rc = DB.search("select * from user_has_securityquestions where securityquestions_questionid='" + a + "' and user_userid='" + k1 + "' and answer='" + answer.getText() + "' ");
                            if (rc.next()) {
                                // startinga();
                                log.info("Logging to system user:" + name.getText());
                                passwordwrong d = new passwordwrong(id.getText());
                                d.setVisible(true);
                                this.dispose();

                            } else {
                                log.warn("Try this user:" + id.getText() + "username:" + name.getText());
                                attempta++;
                                loginAttemptfailda();
                                if (!(attempta == 1)) {
                                    JOptionPane.showMessageDialog(this, "Invalid Data....!");
                                    answer.setText(null);
                                    login l = new login();
                                    l.setVisible(false);
                                    this.dispose();
                                }

                            }
                        }

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else {
                try {

                    String k = id.getText();
                    ResultSet f = DB.search("select * from user where staff_staffid='" + k + "'");
                    if (f.next()) {
                        String k1 = f.getString("userid");
                        ResultSet rc1 = DB.search("select * from securityquestions where question='" + body.getSelectedItem() + "' and status='Active' ");
                        if (rc1.next()) {
                            String a = rc1.getString("questionid");
                            ResultSet rc = DB.search("select * from user_has_securityquestions where securityquestions_questionid='" + a + "' and user_userid='" + k1 + "' and answer='" + answer.getText() + "' ");
                            if (rc.next()) {
                                //    starting();
                                log.info("Logging to system user:" + name.getText());
                                passwordwrong d = new passwordwrong(id.getText());
                                d.setVisible(true);
                                this.dispose();

                            } else {
                                log.warn("Try this user:" + id.getText() + "username:" + name.getText());
                                attempt++;
                                loginAttemptfaild();
                                if (!(attempt == 1)) {
                                    JOptionPane.showMessageDialog(this, "Invalid Data....!");
                                    answer.setText(null);
                                    login l = new login();
                                    l.setVisible(false);
                                    this.dispose();
                                }
                            }
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JComboBox<String> body;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables

    private void starting() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= 100; i++) {
                        if (i == 5) {
                            //send mail
                            dispose();
                        }

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    private void loginAttemptfaild() {
        if (attempt == 1) {
            msg.setText("Please call Your Manager....!");
            try {
                DB.iud("update user set status='Not_valied' where staff_staffid='" + id.getText() + "'");

                JOptionPane.showMessageDialog(this, "Invalid Data....!Please Contact the Admin...!");
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        id.setEnabled(false);
        name.setEnabled(false);
        body.setEnabled(false);
        answer.setEnabled(false);
        login l = new login();
        l.setVisible(false);
        this.dispose();
    }

    private void operation() {
        try {
            ResultSet rs = DB.search("select question from securityquestions");
            while (rs.next()) {
                String s1 = rs.getString("question");
                body.addItem(s1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void startinga() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i <= 100; i++) {
                        if (i == 5) {
                            //send mail
                            dispose();
                        }

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    private void loginAttemptfailda() {
        if (attempt == 1) {
            msg.setText("Please call Your Manager....!");
            try {
                DB.iud("update user set status='loged' where staff_staffid='" + id.getText() + "'");

                JOptionPane.showMessageDialog(this, "Invalid Data....!Please Contact the Admin...!");
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        id.setEnabled(false);
        name.setEnabled(false);
        body.setEnabled(false);
        answer.setEnabled(false);
        login l = new login();
        l.setVisible(false);
        this.dispose();
    }
}
