/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigmafinal;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NipuNa NiraNjaNa
 */
public class studentPortal extends javax.swing.JFrame {

    String ssk;

    /**
     * Creates new form studentPortal
     */
    public studentPortal() {
        initComponents();
        tabSize();
        ssk = MainGUI.serchsid.getText();
        loaddata();
        viewpayment();
        setmarks();
    }

    public studentPortal(String s1) {
        initComponents();
        tabSize();
        loaddata();
        ssk = s1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        portal = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Detail Panel");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Portal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        portal.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        portal.setPreferredSize(new java.awt.Dimension(210, 28));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 260, 30));

        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 100, -1));

        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 230, -1));

        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 240, -1));

        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 230, -1));

        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, -1));

        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 190));

        jLabel15.setText("jLabel15");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 120, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ID card.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, 728, 483));

        portal.addTab("tab1", jPanel3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Student Class Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class ID", "Teacher", "Subject ", "type", "Start Time", "End Time", "Payment"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        portal.addTab("tab2", jPanel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Student Payment Details");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher", "Subject", "Month", "Payment"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        portal.addTab("tab4", jPanel6);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Student Examination Marks");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Teacher", "Marks", "status"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel6.setText("Final Marks");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        portal.addTab("tab3", jPanel5);

        jPanel1.add(portal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 890, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
        //
        int i = jTable3.getSelectedRow();
        String s1 = (String) jTable3.getValueAt(i, 3);
        String s2 = (String) jTable3.getValueAt(i, 0);
        System.out.println(s1);
        if (s1.equals("completed")) {
            //jTextField1.setText(s1);
            // ResultSet rs=DB.search("select * from student_has_exam where student_studentid")
            //jTextField1.setText(null);
            try {
                DB.iud("update student_has_exam set marks='" + jTextField1.getText() + "' where exam_examid='" + s2 + "' and student_studentid='" + jLabel8.getText() + "'");
                dtm.setRowCount(0);
                setmarks();
                jTextField1.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Incomplete Examination");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane portal;
    // End of variables declaration//GEN-END:variables

    private void tabSize() {
        JLabel StudentID = new JLabel("", SwingConstants.CENTER);
        JLabel Attendance = new JLabel("", SwingConstants.CENTER);
        JLabel Marks = new JLabel("", SwingConstants.CENTER);
        JLabel Payment = new JLabel("", SwingConstants.CENTER);

        StudentID.setText("<html><b>Student ID</b></html>");
        Attendance.setText("<html><b>Class<br>Details</b></html>");
        Marks.setText("<html><b>Marks</b></html>");
        Payment.setText("<html><b>Payments</b></html>");

        StudentID.setPreferredSize(new Dimension(120, 80));
        Attendance.setPreferredSize(new Dimension(120, 80));
        Marks.setPreferredSize(new Dimension(120, 80));
        Payment.setPreferredSize(new Dimension(120, 80));

        StudentID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/student id.png")));
        Attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/attendance.png")));
        Marks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/exam.png")));
        Payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/payment.png")));

        portal.setTabComponentAt(0, StudentID);
        portal.setTabComponentAt(1, Attendance);
        portal.setTabComponentAt(3, Marks);
        portal.setTabComponentAt(2, Payment);

    }

    private void loaddata() {
        String s1 = ssk;
        System.out.println("s1");
        try {
            ResultSet rs = DB.search("select * from student where studentid='" + s1 + "'");
            if (rs.next()) {
                String z1 = rs.getString("firstname");
                String z2 = rs.getString("middlename");
                String z3 = rs.getString("lastname");
                String full = z1 + " " + z2 + " " + z3;

                // sa1.setText(full);
                //sb1.setText(full);
                //sc11.setText(z1);
                // sc12.setText(z2);
                // sc13.setText(z3);
                jLabel7.setText(full);

                String zb = rs.getString("nic");
                jLabel8.setText(zb);
                //b2.setText(zb);
                // sc2.setText(zb);
                //  sa12.setText(zb);

                String z5 = rs.getString("img");
                //studentupdate = z5;
                File f = new File(z5);
                Image img = ImageIO.read(f);

                img = img.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
                jLabel13.setIcon(new ImageIcon(img));
                String z6 = rs.getString("dateofbirth");

                //  jLabel12.setText(z6);
                //  sb4.setText(z6);
                SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");

                jLabel12.setText(z6);

                String z7 = rs.getString("gender");
                jLabel15.setText(z7);
                // sb5.setText(z7);

                String k1 = rs.getString("saddress_addressid");
                String k2 = rs.getString("examyear");
                jLabel9.setText(k2);
                // jLabel209.setText(k2);
                // jComboBox4.setSelectedItem(k2);
                String u1 = rs.getString("scontact_contactid");
                //   c15.setSelectedItem(k2);
                //    dsd.setText(k2);
                ResultSet t = DB.search("select * from saddress where addressid='" + k1 + "'");
                if (t.next()) {
                    String z10 = t.getString("city");
                    String z11 = t.getString("street");
                    String z12 = t.getString("no");
                    String z13 = t.getString("zone");
                    String z14 = t.getString("country");

                    jLabel10.setText(z10 + " " + z11 + " " + z12);

                    ResultSet t1 = DB.search("select * from scontact where contactid='" + u1 + "'");
                    if (t1.next()) {
                        String z15 = t1.getString("tp");
                        String z16 = t1.getString("ptn");
                        String z17 = t1.getString("email");
                        jLabel11.setText(z15);

                        //  String j = t4.getString("classregistation_classid");
                        ResultSet a = DB.search("select * from student_has_classregistation where student_studentid='" + s1 + "' and status='Active'");

                        while (a.next()) {

                            String jj = a.getString("classregistation_classid");
                            ResultSet a1 = DB.search("select * from classregistation where classid='" + jj + "' ");

                            if (a1.next()) {
                                //     String e1=a1.getString("")
                                String x = a1.getString("type");
                                String as = a1.getString("subject_has_teacher_subtea_id");

//                                String ks = a1.getString("subject_subjectid");
                                //  ResultSet fin = DB.search("select * from subject where subjectid='" + ks + "'");
                                //  System.out.println(ks);
                                ResultSet h1 = DB.search("select * from subject_has_teacher where subtea_id='" + as + "'  ");
                                if (h1.next()) {
                                    String ms = h1.getString("teacher_teacherid");
                                    String ks = h1.getString("subject_subjectid");
                                    System.out.println(ms);
                                    ResultSet h = DB.search("select * from teacher where teacherid='" + ms + "'  ");
                                    if (h.next()) {
                                        //String bb = h.getString("subject_subjectname");

                                        // String tij = a.getString("subject_subjectname");
                                        DefaultTableModel fu = (DefaultTableModel) jTable1.getModel();
                                        //DefaultTableModel fu1 = (DefaultTableModel) jTable3.getModel();
                                        //  DefaultTableModel fu2 = (DefaultTableModel) setaction.getModel();
                                        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                                        int i = jTable1.getRowCount();
                                        // for (int j = 0; j < i; j++) {
                                        //    String vo1 = (String) jTable1.getValueAt(j, 0);
                                        //    String vo2 = (String) jTable1.getValueAt(j, 1);
                                        //   String vo3 = (String) jTable1.getValueAt(j, 2);
                                        //   String vo4 = (String) jTable1.getValueAt(j, 3);
                                        //   String vo5 = (String) jTable1.getValueAt(j, 4);
                                        //  String vo6 = (String) jTable1.getValueAt(j, 5);
                                        //  String vo7 = (String) jTable1.getValueAt(j, 6);

                                        //  v.add(tr);
                                        try {
                                            ResultSet xx = DB.search("select * from student_has_classregistation where student_studentid='" + s1 + "' and status='Active'");
                                            if (xx.next()) {
                                                String cid = xx.getString("classregistation_classid");
                                                ResultSet z = DB.search("select * from classregistation where classid='" + cid + "'");
                                                if (z.next()) {
//                                                    String si = z.getString("subject_subjectid");
                                                    String ti = z.getString("subject_has_teacher_subtea_id");
                                                    String q = z.getString("Timeslot_timeslotid");
                                                    ResultSet zk = DB.search("select * from subject_has_teacher where subtea_id='" + ti + "'");
                                                    if (zk.next()) {
                                                        String teacherid = zk.getString("teacher_teacherid");
                                                        String si = zk.getString("subject_subjectid");
                                                        ResultSet ah = DB.search("select * from teacher where teacherid='" + teacherid + "'");
                                                        if (ah.next()) {
                                                            String name = ah.getString("name");
                                                            ResultSet d = DB.search("select * from subject where subjectid='" + si + "'");
                                                            if (d.next()) {
                                                                String subjectname = d.getString("subjectname");

                                                                ResultSet sa = DB.search("select * from timeslot where timeslotid='" + q + "'");
                                                                if (sa.next()) {
                                                                    String e1 = sa.getString("time_timeid");
                                                                    String e2 = sa.getString("day_dayid");
                                                                    ResultSet th = DB.search("select * from time where timeid='" + e1 + "'");

                                                                    if (th.next()) {
                                                                        String stime = th.getString("starttime");
                                                                        String etime = th.getString("endtime");
                                                                        ResultSet t1h = DB.search("select * from day where dayid='" + e2 + "'");

                                                                        if (t1h.next()) {

                                                                            DefaultTableModel dtmx = (DefaultTableModel) jTable1.getModel();
                                                                            int ik = dtmx.getRowCount();
                                                                            boolean b = false;
                                                                            String tr = h.getString("name");
                                                                            String bb = d.getString("subjectname");
                                                                            for (int j = 0; j < ik; j++) {
                                                                                String vo1 = (String) jTable1.getValueAt(j, 0);
                                                                                String vo2 = (String) jTable1.getValueAt(j, 1);
                                                                                String vo3 = (String) jTable1.getValueAt(j, 2);
                                                                                String vo4 = (String) jTable1.getValueAt(j, 3);
                                                                                String vo5 = (String) jTable1.getValueAt(j, 4);
                                                                                String vo6 = (String) jTable1.getValueAt(j, 5);
                                                                                String vo7 = (String) jTable1.getValueAt(j, 6);

                                                                                if (vo1.equals(jj) && vo2.equals(tr) && vo3.equals(bb) && vo4.equals(x) && vo5.equals(stime) && vo6.equals(etime) && vo7.equals(d.getString("payment"))) {

                                                                                    b = true;
                                                                                }

                                                                            }
                                                                            if (b == false) {
                                                                                Vector v = new Vector();
                                                                                // Vector v1 = new Vector();

                                                                                System.out.println(tr);

                                                                                System.out.println(bb);
                                                                                v.add(jj);
                                                                                v.add(tr);
                                                                                v.add(bb);
                                                                                v.add(x);
                                                                                String daydetails = t1h.getString("date");
                                                                                v.add(stime);
                                                                                v.add(etime);
                                                                                v.add(d.getString("payment"));
                                                                                fu.addRow(v);
                                                                                // fu.addRow(v);
                                                                                // zz.jLabel14.setText(z.getString("type"));
                                                                                //  zz.jLabel15.setText(subjectname);
                                                                            }

                                                                        }
                                                                    }

                                                                }

                                                            }

                                                        }

                                                    }

                                                }
                                            }

                                        } catch (Exception e) {
                                            e.printStackTrace();
                                        }
                                        // v1.add(true);
                                        // v1.add(bb);
                                        //  v1.add(tr);
                                        //  v1.add(x);

                                        //  fu1.addRow(v);
                                        // fu2.addRow(v1);
                                        // setupdatesubject();
                                        // }
                                    }
                                }

                            }
                        }
                    }

                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Invalid Data...!");
                //  clearfield();
                //  setfield();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void viewpayment() {
        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            // Vector v=new Vector();
            //  String subject = tk1.getString("subjectid");
            ResultSet tk11 = DB.search("select * from invoice where student_studentid='" + jLabel8.getText() + "'");
            while (tk11.next()) {
                System.out.println("asas");
                String tid = tk11.getString("teacher_teacherid");
                String sub = tk11.getString("subject_subjectid");
                ResultSet w = DB.search("select * from teacher where teacherid='" + tid + "'");
                if (w.next()) {

                    ResultSet w1 = DB.search("select * from subject where subjectid='" + sub + "'");
                    if (w1.next()) {
//                        System.out.println(searchsid.getText());
//                        System.out.println(subject);
//                        System.out.println(teacher);
                        String sid = tk11.getString("payment_paymentid");
                        System.out.println(sid);

                        ResultSet t = DB.search("select * from payment   where paymentid='" + sid + "' ORDER BY paymentid DESC ");
                        if (t.next()) {
                            Vector v = new Vector();
                            v.add(w.getString("name"));
                            v.add(w1.getString("subjectname"));

                            //  v.add(t.getString("year"));
                            v.add(t.getString("month"));
                            v.add(t.getString("paidamount"));
                            dtm.addRow(v);
                        }
                    }

                }
            }
            ResultSet t1 = DB.search("select * from admission   where student_studentid='" + jLabel8.getText() + "'  ");
            if (t1.next()) {
                Vector v = new Vector();
                v.add("Institite fees");
                v.add(t1.getString("date"));
                v.add(t1.getString("payment"));

                //  v.add(t.getString("year"));
                v.add("paid");
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void setmarks() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            ResultSet rs = DB.search("select * from student_has_exam where student_studentid='" + jLabel8.getText() + "'");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("exam_examid"));

                //  v.add(rs.getString("exam_examid"));
                ResultSet s = DB.search("select * from exam where examid='" + rs.getString("exam_examid") + "'");
                if (s.next()) {
                    String s1 = s.getString("teacher_teacherid");
                    ResultSet as = DB.search("select * from teacher where teacherid='" + s1 + "'");
                    if (as.next()) {
                        v.add(as.getString("name"));
                    }

                }

                v.add(rs.getString("marks"));
                v.add(rs.getString("status"));
                dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
