/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigmafinal;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author danushka nandalochan
 */
public class studentattendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */
    public studentattendance() {
        initComponents();
        setdateandtime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        msg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 330, 200));

        time.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 330, 200));

        empid.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        empid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        getContentPane().add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 870, 120));

        msg.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 51), new java.awt.Color(153, 255, 51), new java.awt.Color(153, 255, 153), new java.awt.Color(51, 255, 102)));
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 870, 120));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        int setslot = 0;
        try {
            ResultSet rs = DB.search("select * from student where studentid='" + empid.getText() + "'");
            if (rs.next()) {
                String full = rs.getString("firstname") + " " + rs.getString("middlename") + " " + rs.getString("lastname");
            //    String j = rs.getString("indexid");
                String ew = rs.getString("studentid");
                System.out.print(full);
                try {

                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("a");
                    String am = sdf.format(d);
                    SimpleDateFormat sdf1 = new SimpleDateFormat("hh");
                    Date date1 = new Date();
                    SimpleDateFormat sss = new SimpleDateFormat("EEEE");
                    String x = sss.format(date1);

                    String ti = sdf1.format(d);
                    int s = Integer.parseInt(ti);
                    if (am == "PM") {
                        if (s == 12) {

                            setslot = 2;
                        }

                        if (s < 1) {
                            setslot = 2;

                        } else if (s < 8 && s < 12) {
                            setslot = 3;

                        }

                    } else {
                        if (s < 7) {
                            setslot = 1;

                        }

                    }
                    System.out.println("111212sssssss");
                    ResultSet ff = DB.search("select * from day where date ='" + x + "'");
                    if (ff.next()) {
                        System.out.println("sssssss");
                        String da = ff.getString("dayid");
                        ResultSet sl = DB.search("select * from timeslot where time_timeid='" + setslot + "' and day_dayid='" + da + "'");
                        if (sl.next()) {
                            System.out.println("dsdsds");
                            String sdi = sl.getString("timeslotid");
                            ResultSet dda = DB.search("select * from classregistation where Timeslot_timeslotid='" + sdi + "'");
                            while (dda.next()) {
                                System.out.println("11111");
                                String qw = dda.getString("classid");
                                ResultSet dw = DB.search("select * from student_has_classregistation where classregistation_classid='" + qw + "'");
                                if (dw.next()) {
                                    System.out.println("ewewe");
                                    String fid = dw.getString("studentsubjectid");
                                    DB.iud("insert into attendence (student_studentid,date,intime,staus,attendenceid,student_has_classregistation_studentsubjectid) Values('" + ew + "','" + date.getText() + "','" + time.getText() + "','present','" + empid.getText() + "','" + fid + "')");
                                    msg.setText(full + " " + "Welcome to Claa Room,Have a Nice Day");
                                }

                            }

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Invalid Class...!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Invalid Class...!");
                    }

                } catch (java.sql.SQLException ex) {
                    // ex.printStackTrace();
                    try {
                        ResultSet rs2 = DB.search("select staus from attendence where student_studentid='" + empid.getText() + "' and date='" + date.getText() + "'");
                        if (rs2.next()) {
                            System.out.println("dsfd");
                            if (!rs2.getString("staus").equals("out")) {
                                DB.iud("update attendence set outtime='" + time.getText() + "',staus='out' where student_studentid='" + empid.getText() + "' and date='" + date.getText() + "'");
                                empid.setText(null);
                                msg.setText(full + " " + "Good bye....!");
                            } else {
                                System.out.println("fdfdfeee");
                                msg.setText(full + " " + "You already exit");
                            }

                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                msg.setText("Unauthorized Access...!");
                empid.setText(null);

            }
        } catch (Exception e1) {
            e1.printStackTrace();
        }
        clearField();
    }//GEN-LAST:event_empidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login w = new login();
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentattendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentattendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTextField empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    private void clearField() {
        Thread c = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(3000);
                    empid.setText(null);
                    msg.setText(null);

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        });
        c.start();
    }

    private void setdateandtime() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY:MM:dd");
        String da = sdf.format(d);
        date.setText(da);
        SimpleDateFormat sdf1 = new SimpleDateFormat("hh:mm:ss:a");
        String ti = sdf1.format(d);
        time.setText(ti);
        empid.grabFocus();
    }
}
