package enigmafinal;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NipuNa NiraNjaNa
 */
public class teacherpayment extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public teacherpayment() {
        initComponents();
        setyear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jTextField38 = new javax.swing.JTextField();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel168 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel169 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton31 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jLabel167 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel171 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel73.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Teacher Information"));
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField38ActionPerformed(evt);
            }
        });
        jPanel73.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 240, -1));

        jLabel175.setText("NIC Number");
        jPanel73.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 300, 50));

        jLabel176.setText("Teacher NIC Number:");
        jPanel73.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 160, 30));

        jPanel74.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel74.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 200));

        jPanel73.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 220));

        jLabel177.setText("NIC :");
        jPanel73.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel178.setText("Teacher Registered Name:");
        jPanel73.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 50));

        jLabel179.setText("Teacher Name");
        jPanel73.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 50));

        getContentPane().add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 520, 340));

        jPanel72.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payment Details"));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "class ID", "Class Name", "No. of Students", "Class Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel72.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 90));

        jLabel4.setText("Year");
        jPanel72.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, 30));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox10ItemStateChanged(evt);
            }
        });
        jPanel72.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        jLabel5.setText("Class ID:");
        jPanel72.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 20));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel72.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 20));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox11ItemStateChanged(evt);
            }
        });
        jPanel72.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        jLabel7.setText("month");
        jPanel72.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 30));

        jPanel72.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 140, -1));

        getContentPane().add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 460, 200));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel168.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel168.setForeground(new java.awt.Color(255, 255, 255));
        jLabel168.setText("Teacher Payments");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel168)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel168)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 70));

        jPanel71.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payment Amendments"));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel169.setText("Total count:");
        jPanel71.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 40));

        jLabel174.setText("Comment");
        jPanel71.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane10.setViewportView(jTextArea1);

        jPanel71.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, -1));

        jButton31.setText("Generate");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel71.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 30));

        jButton47.setText("Generate");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel71.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 30));

        jLabel167.setText("Institute Fee (Per Student)");
        jPanel71.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        jTextField10.setEditable(false);
        jPanel71.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 190, -1));

        jLabel3.setText("Total Income");
        jPanel71.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, 20));

        jLabel170.setText(" Total Income :");
        jPanel71.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 40));

        jLabel2.setText("count");
        jPanel71.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 90, 30));

        getContentPane().add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 390, 340));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox9ItemStateChanged(evt);
            }
        });
        jComboBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox9MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 140, -1));

        jLabel171.setText("Month");
        getContentPane().add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 60, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Class Name", "No. of Students", "Class Payment"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 410, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int i = dtm.getRowCount();
        int totpaay = 0;
        int totcount = 0;
        for (int j = 0; j < i; j++) {
            boolean b = (boolean) jTable2.getValueAt(j, 0);
            int s1 = (int) jTable2.getValueAt(j, 4);

            int s2 = (int) jTable2.getValueAt(j, 3);
            // int h1 = s2;
            if (b == true) {
                totpaay += s1;
                totcount += s2;
            }

        }
        System.out.println(totpaay);
        System.out.println(totcount);
        jLabel2.setText("" + totcount);
        int y = Integer.parseInt(jTextField10.getText());
        int z = totpaay * totcount;
        int xx = z * y;
        int cc = xx / 100;
        cc = totpaay - cc;
        jLabel3.setText("" + cc);

    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int i = dtm.getRowCount();
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY:MM:dd");
        String da = sdf.format(d);
        SimpleDateFormat sdfe = new SimpleDateFormat("MM");
        String mon = sdfe.format(d);
        //  int totpaay = 0;
        //  int totcount = 0;
        for (int j = 0; j < i; j++) {
            boolean b = (boolean) jTable2.getValueAt(j, 0);
            String s1 = (String) jTable2.getValueAt(j, 1);

            if (b == true) {
                try {

//        
                    ResultSet s = DB.search("select * from invoice where classid='" + s1 + "' and teacherpaid='0'");
                    while (s.next()) {
                        ResultSet sw = DB.search("select * from payment where paymentid='" + s.getString("payment_paymentid") + "' and month='" + jComboBox10.getSelectedItem() + "' and year='" + jComboBox2.getSelectedItem() + "'");
                        if (sw.next()) {
                            String sd = sw.getString("paymentid");
                            //   DB.iud("update payment set  where paymentid='" + s.getString("payment_paymentid") + "' and month='" + jComboBox10.getSelectedItem() + "' and year='" + jComboBox2.getSelectedItem() + "'");
                            DB.iud("update invoice set teacherpaid='1' where payment_paymentid='" + sd + "'");
                        }
                        ResultSet rs = DB.search("select count(paymentid) as x from teacherpayment  ");
                        if (rs.next()) {
                            int il = Integer.parseInt(rs.getString("x"));
                            il++;
                            ResultSet ds=DB.search("select * from teacher where NIC_number='"+ jTextField38.getText() +"'");
                            if(ds.next()){
                                  ResultSet ds1=DB.search("select * from staff where nic='"+  MainGUI.email.getText() +"'");
                            if(ds1.next()){
                                 ResultSet ds2=DB.search("select * from user where staff_staffid='"+  ds1.getString("staffid") +"'");
                            if(ds2.next()){
                            DB.iud("insert into teacherpayment values('" + il + "','" + da + "','" + jLabel3.getText() + "','" +ds.getString("teacherid")+ "','" +ds2.getString("userid") + "','" + s1 + "','" + mon + "','Active','" + jLabel2.getText() + "','" + jTextArea1.getText() + "')");
                        }}}
                        }
                    }

                } catch (Exception e) {
                    e.printStackTrace();

                }
            }

        }
        clearfield();
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        jComboBox1.removeAllItems();
//           int month = Integer.parseInt((String) jComboBox35.getSelectedItem());
//                int year = Integer.parseInt(w3.getText());
//                int pm = month;
//                int py = year;
//                if (month == 1) {
//                    month = 12;
//                    year = year - 1;
//                } else {
//
//                    month--;
//
//                }
        try {
            ResultSet rs = DB.search("select * from teacher where NIC_number='" + jTextField38.getText() + "'");
            if (rs.next()) {
                jLabel179.setText(rs.getString("title") + " " + rs.getString("name"));
                //   jComboBox31.setSelectedItem(rs.getString("status"));
                //    newpath1 = rs.getString("img");
                File f = new File(rs.getString("img"));
                Image img = ImageIO.read(f);
                // updateteacher = rs.getString("img");
                //  jComboBox6.setSelectedItem();
                img = img.getScaledInstance(jPanel74.getWidth(), jPanel74.getHeight(), Image.SCALE_SMOOTH);
                jLabel1.setIcon(new ImageIcon(img));
                SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
                jLabel175.setText(jTextField38.getText());
                String d = rs.getString("teacherid");

                jTextField10.setText(rs.getString("deduction"));
                ResultSet rsl = DB.search("select * from subject_has_teacher where teacher_teacherid='" + d + "'");
                while (rsl.next()) {
                    ResultSet h = DB.search("select * from classregistation where subject_has_teacher_subtea_id='" + rsl.getString("subtea_id") + "'");
                    if (h.next()) {
                        jComboBox1.addItem(h.getString("classid"));
                    }
                }

                ResultSet rsk = DB.search("select * from teacherpayment where teacherid='" + jTextField38.getText() + "'");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                if (rsk.next()) {
                    Vector v = new Vector();
                    v.add(rsk.getString("status"));
                    ResultSet rsj = DB.search("select * from classregistation where classid='" + rsk.getString("classregistation_classid") + "'");
                    if (rsj.next()) {
                        ResultSet df = DB.search("select * from subject_has_teacher where subtea_id='" + rsj.getString("subject_has_teacher_subtea_id") + "'");
                        if (df.next()) {
                            ResultSet po = DB.search("select * from subject where subjectid='" + df.getString("subject_subjectid") + "'");
                            v.add("classid" + ":" + rsk.getString("classregistation_classid") + " " + po.getString("subjectname") + " " + rsk.getString("type"));
                        }
                    }
                    v.add(rsk.getString("count"));
                    v.add(rsk.getString("payment"));
                    v.add(v);
                }

//                zz5.setText(rs1.getString("land"));
//                zz6.setText(rs1.getString("email"));
//
//                zz1.setText(rs2.getString("city"));
//                zz2.setText(rs2.getString("street"));
//                zz3.setText(rs2.getString("no"));
//                searchteachersubject();
//                addallsubjects();
                ResultSet rsj = DB.search("select * from subject_has_teacher where teacher_teacherid='" + jTextField38.getText() + "'");
                while (rsj.next()) {
                    ResultSet r = DB.search("select * from classregistation where subject_has_teacher_subtea_id='" + rsj.getString("subtea_id") + "'");
                    while (r.next()) {
//                    ResultSet s=DB.search("selct * from invoice where classid='"+r.getString("classid")+"'");
//                            if(s.next()){
//                            
//                            }
                        jComboBox1.addItem(r.getString("classid"));

                    }
                }
                DefaultTableModel dtmd = (DefaultTableModel) jTable2.getModel();
                dtmd.setRowCount(0);

            } else {

                JOptionPane.showMessageDialog(rootPane, "Invalid data...!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jComboBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox9ItemStateChanged
        try {
             ResultSet rs = DB.search("select * from teacher where NIC_number='" + jTextField38.getText() + "'");
            if (rs.next()) {
          
                String d = rs.getString("teacherid");
        try {
            ResultSet rsk = DB.search("select * from teacherpayment where teacherid='" + d + "' and month='" + jComboBox9.getSelectedItem() + "'");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            if (rsk.next()) {
                Vector v = new Vector();
                v.add(rsk.getString("status"));
                ResultSet rsj = DB.search("select * from classregistation where classid='" + rsk.getString("classregistation_classid") + "'");
                if (rsj.next()) {
                    ResultSet df = DB.search("select * from subject_has_teacher where subtea_id='" + rsj.getString("subject_has_teacher_subtea_id") + "'");
                    if (df.next()) {
                        ResultSet po = DB.search("select * from subject where subjectid='" + df.getString("subject_subjectid") + "'");
                       if(po.next()){
                        v.add("classid" + ":" + rsk.getString("classregistation_classid") + " " + po.getString("subjectname") + " " + rsj.getString("type"));
                    }}
                }
                v.add(rsk.getString("count"));
                v.add(rsk.getString("payment"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }}
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox9ItemStateChanged

    private void jComboBox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox10ItemStateChanged


    }//GEN-LAST:event_jComboBox10ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try {

//            ResultSet rsj = DB.search("select * from subject_has_teacher where teacher_teacherid='" + jTextField38.getText() + "'");
//            while (rsj.next()) {
//                
//                ResultSet r = DB.search("select * from classregistation where subject_has_teacher_subtea_id='" + rsj.getString("subtea_id") + "'");
//                while (r.next()) {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            int totpay = 0;
            int scount = 0;
            ResultSet s = DB.search("select * from invoice where classid='" + jComboBox1.getSelectedItem() + "' and teacherpaid='0'");
            if (s.next()) {
                ResultSet sw = DB.search("select paidamount from payment where paymentid='" + s.getString("payment_paymentid") + "' and month='" + jComboBox10.getSelectedItem() + "' and year='" + jComboBox2.getSelectedItem() + "'");
                while (sw.next()) {
                    scount++;
                    System.out.println(scount);
                    //  ;
                    String pp = sw.getString("paidamount");
                    totpay += Integer.parseInt(pp);
                    System.out.println("paid" + totpay);
                    System.out.println(sw.getString("paidamount"));
                }
                Vector v = new Vector();
                v.add(false);
                v.add(jComboBox1.getSelectedItem());
                ResultSet sww = DB.search("select * from classregistation where classid='" + jComboBox1.getSelectedItem() + "' ");
                if (sww.next()) {
                    String p = sww.getString("Timeslot_timeslotid");
                    ResultSet sww1 = DB.search("select * from timeslot where timeslotid='" + p + "' ");
                    if (sww1.next()) {
                        //String p1=sww1.getString("timeslot");
                        ResultSet sww2 = DB.search("select * from day where dayid='" + sww1.getString("day_dayid") + "' ");
                        if (sww2.next()) {
                            //String p1=sww1.getString("timeslot");
                            ResultSet sww3 = DB.search("select * from time where timeid='" + sww1.getString("time_timeid") + "' ");
                            if (sww3.next()) {
                                //String p1=sww1.getString("timeslot");
                                v.add(sww2.getString("date") + " " + sww3.getString("starttime") + " " + sww3.getString("endtime"));

                            }

                        }

                    }
                }
                // v.add(jComboBox1.getSelectedItem());
                v.add(scount);
                v.add(totpay);
                dtm.addRow(v);
            }
            // }
            //  }
            //  jComboBox1.addItem(r.getString("classid"));
        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox11ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        try {

//            ResultSet rsj = DB.search("select * from subject_has_teacher where teacher_teacherid='" + jTextField38.getText() + "'");
//            while (rsj.next()) {
//                
//                ResultSet r = DB.search("select * from classregistation where subject_has_teacher_subtea_id='" + rsj.getString("subtea_id") + "'");
//                while (r.next()) {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            int totpay = 0;
            int scount = 0;
            ResultSet s = DB.search("select * from invoice where classid='" + jComboBox1.getSelectedItem() + "' and teacherpaid='0'");
            if (s.next()) {
                ResultSet sw = DB.search("select paidamount from payment where paymentid='" + s.getString("payment_paymentid") + "' and month='" + jComboBox10.getSelectedItem() + "' and year='" + jComboBox2.getSelectedItem() + "'");
                while (sw.next()) {
                    scount++;
                    System.out.println(scount);
                    //  ;
                    String pp = sw.getString("paidamount");
                    totpay += Integer.parseInt(pp);
                    System.out.println("paid" + totpay);
                    System.out.println(sw.getString("paidamount"));
                }
                Vector v = new Vector();
                v.add(false);
                v.add(jComboBox1.getSelectedItem());
                ResultSet sww = DB.search("select * from classregistation where classid='" + jComboBox1.getSelectedItem() + "' ");
                if (sww.next()) {
                    String p = sww.getString("Timeslot_timeslotid");
                    ResultSet sww1 = DB.search("select * from timeslot where timeslotid='" + p + "' ");
                    if (sww1.next()) {
                        //String p1=sww1.getString("timeslot");
                        ResultSet sww2 = DB.search("select * from day where dayid='" + sww1.getString("day_dayid") + "' ");
                        if (sww2.next()) {
                            //String p1=sww1.getString("timeslot");
                            ResultSet sww3 = DB.search("select * from time where timeid='" + sww1.getString("time_timeid") + "' ");
                            if (sww3.next()) {
                                //String p1=sww1.getString("timeslot");
                                v.add(sww2.getString("date") + " " + sww3.getString("starttime") + " " + sww3.getString("endtime"));

                            }

                        }

                    }
                }
                // v.add(jComboBox1.getSelectedItem());
                v.add(scount);
                v.add(totpay);
                dtm.addRow(v);
            }
            // }
            //  }
            //  jComboBox1.addItem(r.getString("classid"));
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox9MouseClicked
         try {
            ResultSet rsk = DB.search("select * from teacherpayment where teacherid='" + jTextField38.getText() + "' and month='" + jComboBox9.getSelectedItem() + "'");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            if (rsk.next()) {
                Vector v = new Vector();
                v.add(rsk.getString("status"));
                ResultSet rsj = DB.search("select * from classregistation where classid='" + rsk.getString("classregistation_classid") + "'");
                if (rsj.next()) {
                    ResultSet df = DB.search("select * from subject_has_teacher where subtea_id='" + rsj.getString("subject_has_teacher_subtea_id") + "'");
                    if (df.next()) {
                        ResultSet po = DB.search("select * from subject where subjectid='" + df.getString("subject_subjectid") + "'");
                        v.add("classid" + ":" + rsk.getString("classregistation_classid") + " " + po.getString("subjectname") + " " + rsk.getString("type"));
                    }
                }
                v.add(rsk.getString("count"));
                v.add(rsk.getString("payment"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherpayment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherpayment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherpayment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherpayment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton47;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField38;
    // End of variables declaration//GEN-END:variables

    private void setyear() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY");
        String date = sdf.format(d);
        int i = Integer.parseInt(date);
        i = i - 5;
        for (int j = 0; j < 10; j++) {
            int k = i + j;
            System.out.println(k);
            jComboBox2.addItem("" + k);
           // jComboBox3.addItem("" + k);
        }
    }

    private void clearfield() {
        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        jTextField38.setText(null);
        jLabel1.setIcon(null);
        jLabel179.setText(null);
        jLabel175.setText(null);
        jComboBox1.removeAllItems();
        //jComboBox1.removeAllItems();
        // jComboBox1.removeAllItems();
        jComboBox10.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        jTextField10.setText(null);
        jLabel3.setText(null);
        jLabel2.setText(null);
        jTextArea1.setText(null);
        jComboBox9.setSelectedIndex(0);
        DefaultTableModel dtmx = (DefaultTableModel) jTable1.getModel();
        dtmx.setRowCount(0);
    }
}
